[package]
name = "eggnett-client"
version = "1.0.0"
authors = ["Paskeharen <github.com/paskeharen>"]
edition = "2018"

[dependencies]
clap = "2.33"
crossterm = "0.19"
md5 = "0.7"
reqwest = { version = "0.11", features = ["blocking"] }
